---
- name: Install Gitlab cli dependencies
  yum: name={{ item }} state=latest
  with_items:
  - python-psycopg2
  - python-pip

- name: Install Gitlab cli
  pip: name={{ item }} state=latest
  with_items:
  - python-gitlab
  
 
